"--------------------------------------"
"   _   _ ________  _________  _____   "
"  | | | |_   _|  \/  || ___ \/  __ \  "
"  | | | | | | | .  . || |_/ /| /  \/  "
"  | | | | | | | |\/| ||    / | |      "
"  \ \_/ /_| |_| |  | || |\ \ | \__/\  "
"   \___/ \___/\_|  |_/\_| \_| \____/  "
"                                      "
"--------------------------------------"

" Color Customization
colorscheme calm

let g:airline_highlighting_cache = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_close_button = 0
let g:airline_theme='calm'

" If filetype is text or markdown, set spellcheck
autocmd Filetype text setlocal spell
autocmd Filetype markdown setlocal spell

" If filetype is html, highlight TODO, FIXME, and XXX if it is in a comment
autocmd Filetype html syn keyword htmlCommentTodo TODO FIXME XXX containedin=htmlComment contained
autocmd Filetype html hi def link htmlCommentTodo Todo


" Vim options
set hidden                      " Can switch buffers without saving

map <C-w>t :tab terminal<CR>
nnoremap <M-Left> <C-O>
nnoremap <M-Right> <C-I>

set ttyfast                     " Terminal acceleration

set noshowmode                  " Since we are using airline, this will disable prompts of which mode we are in
set backspace=indent,eol,start  " Backspace over everything

set number relativenumber       " Current line is current line number, the rest of the line numbers are relative to it
set numberwidth=2               " Make number column default a width two

set wildmenu                    " Display a list of possible commands/attributes when tab is pressed

set cursorline                  " Highlight current line/line-number

set ignorecase                  " Ignore case while searching
set smartcase                   " Be smart about cases when searching
set hlsearch                    " Highlight search hits
set incsearch                   " Search similar to browsers

set showmatch                   " Show matching brackets when hovering over a bracket

set autoindent                  " Auto indent
set smartindent                 " Smart indent

set nowrap                      " Wrap lines

set expandtab                   " Coverts tabs into spaces
set tabstop=4                   " How long is tab
set shiftwidth=4                " How long is Shift<-, or Shift->

set laststatus=2                " Always show status line

let g:netrw_list_hide= '.*\.swp$,.DS_Store,*/tmp/*,*.so,*.swp,*.zip,*.git,^\.\.\=/\=$' " Hide *.swp files in Netrw


" Display highlight group on cursor
function! SynStack()
  if !exists("*synstack")
    return
  endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc
